### PR TITLE
Support identify call and advertising identifiers

### PR DESCRIPTION
**Pull request by curtisliu**

### CODE REVIEW

**Comment by DirtyAnalytics** [comment]
@f2prateek @amillet89 can we merge this one in? quite a few requests for this from customers

**Comment by f2prateek** [comment]
:shipit: , thanks @curtisliu !

**Comment by f2prateek** [comment]
@DirtyAnalytics I'm heading to bed now, but remind me to deploy this tomorrow in case I forget.

**Comment by DirtyAnalytics** [comment]
haha sounds good buddy I'll check in tomorrow

**Comment by f2prateek** [comment]
Deployed in 1.0.9

**Pull request merged**
