### PR TITLE
Support identify

### PR DESCRIPTION
**Pull request by f2prateek**
Had to reopen since tests were failing.

### CODE REVIEW

**Comment by DirtyAnalytics** [comment]
@f2prateek should amplitude identify be working now as far as you know? I am helping rdio to debug some issues right now with Amplitude support

**Comment by f2prateek** [comment]
@DirtyAnalytics   Haven't released this yet sorry, going out today.

**Comment by DirtyAnalytics** [comment]
@f2prateek is this deployed?

**Comment by f2prateek** [comment]
Yup!

**Pull request merged**
