### PR TITLE
Add library field to events

### PR DESCRIPTION
**Pull request by knorwood**

### CODE REVIEW

**Comment by f2prateek** [comment]
Is there any documentation about the library field in Amplitude's docs?

**Comment by knorwood** [comment]
Hi @f2prateek,

The library field is intended for internal use, there's no need for any customers to set it themselves so we don't intend to add it to any docs.

Thanks,
Kurt

**Comment by f2prateek** [comment]
@knorwood To clarify - this is for internal use by use as a customer, or for Amplitude (sorry wasn't sure where you work)?

**Comment by knorwood** [comment]
@f2prateek Sorry for not making that clear, I work at Amplitude. It should be listed under my organizations on my profile page.

Thanks,
Kurt

**Comment by f2prateek** [comment]
cool!

**Comment by paladin8** [comment]
@f2prateek Just checking in; do you have a timeline for deploying this to production? Not super urgent, but sometime in the next couple of weeks would be great. Thanks!

**Comment by sperand-io** [comment]
@paladin8 releasing now :) holler if you're not seeing this field by this afternoon.

**Pull request merged**
